# site info
url: cherryleer.com
baseurl: ""
author: "Cherryleer"
title: Cherryleer's Blog
description: 这是Cherryleer的个人博客。
email: cherryleer@gmail.com
github: cherryleer
permalink: /:year/:month/:day/:title
android: http://cherryleer.com/assets/app/Cherryleer-blog-0.0.1.apk
ios: http://cherryleer.com/assets/app/Cherryleer-blog-0.0.1.ipa

qiniu_static: http://7xkso7.com1.z0.glb.clouddn.com

# Comment
disqus_shortname: cherryleercom

# Build settings
markdown: kramdown
sass:
  style: compressed

